version: '3'
services:
  server:
    container_name: server
    build: ./nginx
    ports:
      - "8001:8001"
    depends_on:
      - web
    networks:
      - app-ws
    stdin_open: true
    tty: true
  web:
    container_name: app
    build: .
    environment:
      NODE_ENV: production
      TZ: "Asia/Manila"
    volumes:
      - ./project:/app
      - /app/node_modules
      - ./project/tmp:/app/tmp
    networks:
      - app-ws
    stdin_open: true
    tty: true
networks:
  app-ws:
    driver: bridge